server:
  port: 8081
spring:
  application:
    name: ms-product-service
  redis:
    host: 0.0.0.0
    port: 6379
  data:
    mongodb:
      uri: "${MONGO_URI:mongodb+srv://mario:mario@cluster0.t4gtdev.mongodb.net/}"
      database: product
api:
  url:
    ms-company-service: http://ms-company-service

