server:
  port: 8081
spring:
  application:
    name: ms-product-service

  data:
    mongodb:
      uri: "mongodb+srv://mario:mario@cluster0.t4gtdev.mongodb.net/"
      database: product
api:
  url:
    ms-company-service: http://ms-company-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8079/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-product-service