server:
  port: 8081
spring:
  application:
    name: ms-product-service

  data:
    mongodb:
      uri: "${MONGO_URI:mongodb+srv://mario:mario@cluster0.t4gtdev.mongodb.net/}"
      database: product
api:
  url:
    ms-company-service: lb://ms-company-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8079/eureka
  instance:
    preferIpAddress: true
    hostname: ms-product-service